---
name: terrascan

on:
  pull_request:
    branches: [main]

env:
  TEMPLATE_REPOSITORY: telekom-mms/terraform-template

jobs:
  call-terrascan:
    if: github.repository != '$TEMPLATE_REPOSITORY'
    uses: telekom-mms/.github/.github/workflows/terrascan.yml@main
    with:
      iac_type: terraform
      iac_dir: ./tests
      policy_type: azure
      non_recursive: true
